### ISSUE TITLE
Error while uploading a JSON file

### ISSUE THREAD

**Issue by PlkMarudny** [h3rald/litestore#59] opened 2020-12-06 08:04 UTC
Hi,

I am trying to upload the JSON document:

`{
	"_id": "templates",
	"_rev": "55-99fee0600aa5868943ab321ce33b1ec2",
	"modified": "",
	"templates": [{
		"value": "2001",
		"valueName": "2000",
		"channel": "news",
		"label": "Breaking News",
		"vShift": "110%",
		"hShift": "50%",
		"stopPoint": "$pilot1",
		"type": "vcp",
		"mappings": {
			"conceptvariantchoice": {
				"Concept": "PreviewTicker",
				"Variant": "Default"
			},
			"layers": [{
				"layerId": "-vizlayer-BreakingNews_______",
				"layer": "BreakingTickerIN"
			}],
			"fields": ["BreakingText"]
		},
		"profiles": ["http://10.20.67.42:8580/profiles/BLMCH1A", "http://10.20.67.43:8580/profiles/BLMCH1B", "http://10.20.67.45:8580/profiles/TXMOB1B"]
	}, {
		"value": "2003",
		"valueName": "2002",
		"channel": "news",
		"label": "Extreme Breaking News",
		"vShift": "110%",
		"hShift": "50%",
		"stopPoint": "$pilot1",
		"type": "vcp",
		"mappings": {
			"conceptvariantchoice": {
				"Concept": "PreviewTicker",
				"Variant": "Default"
			},
			"layers": [{
				"layerId": "-vizlayer-BreakingNews_______",
				"layer": "ExtremeBreakingTickerIN"
			}],
			"fields": ["BreakingText"]
		},
		"profiles": ["http://10.20.67.42:8580/profiles/BLMCH1A", "http://10.20.67.43:8580/profiles/BLMCH1B", "http://10.20.67.45:8580/profiles/TXMOB1B"]
	}, {
		"value": "2005",
		"valueName": "2004",
		"channel": "business",
		"label": "Bloomberg Breaking News",
		"vShift": "110%",
		"hShift": "50%",
		"stopPoint": "$pilot1",
		"type": "vcp",
		"mappings": {
			"conceptvariantchoice": {
				"Concept": "PreviewTicker",
				"Variant": "Default"
			},
			"layers": [{
				"layerId": "-vizlayer-BloombergBreaking__",
				"layer": "BBreakingTickerIN"
			}],
			"fields": ["BreakingText"]
		},
		"profiles": ["http://10.20.67.42:8580/profiles/BLMCH1A", "http://10.20.67.43:8580/profiles/BLMCH1B", "http://10.20.67.45:8580/profiles/TXMOB1B"]
	}, {
		"value": "2007",
		"valueName": "2006",
		"channel": "business",
		"label": "Bloomberg Extreme Breaking News",
		"vShift": "110%",
		"hShift": "50%",
		"stopPoint": "$pilot1",
		"type": "vcp",
		"mappings": {
			"conceptvariantchoice": {
				"Concept": "PreviewTicker",
				"Variant": "Default"
			},
			"layers": [{
				"layerId": "-vizlayer-BExtremeBreaking___",
				"layer": "BExtremeBreakingTickerIN"
			}],
			"fields": ["BreakingText"]
		},
		"profiles": ["http://10.20.67.42:8580/profiles/BLMCH1A", "http://10.20.67.43:8580/profiles/BLMCH1B", "http://10.20.67.45:8580/profiles/TXMOB1B"]
	}]
}`

an getting an error:

![image](https://user-images.githubusercontent.com/4361591/101274885-1f642180-37bb-11eb-8f48-66013382dfb2.png)

The JSON seems to be valid.

**Comment by PlkMarudny** [comment] 2020-12-10 10:30
From the GUI, of course.

**Comment by h3rald** [comment] 2020-12-10 12:57
Yes I assumed that... otherwise it would have been a tragedy ;) lemme take another look at that, I'll hopefully be able to fix it when I get a little bit of time

**Comment by h3rald** [comment] 2020-12-14 19:50
I investigated a little bit and I was able to reproduce the error only if I didn't check the **Text File** checkbox... if you check it (and you should because you are uploading a text file) no error occurs 😊 

Hope this helps,


![image](https://user-images.githubusercontent.com/1169/102128315-f80df400-3e4d-11eb-88af-aedfe65e2bc3.png)

**Comment by PlkMarudny** [comment] 2020-12-15 11:10
But I do copy/paste and just pressing "save". In such a case: error.

**Comment by h3rald** [comment] 2020-12-15 19:31
Alright I tried to just copy and paste the json and the only time I got an error (but not the same one) was when I didn't specify "application/json" as content type... otherwise it seems to work as expected...

![image](https://user-images.githubusercontent.com/1169/102263349-7765fb00-3f14-11eb-8989-3ae353d43a06.png)

**Comment by h3rald** [comment] 2021-04-13 20:11
Closing for now, it seems to work.

**Closed as completed by h3rald** 2021-04-13 20:11 UTC
